#!/usr/bin/env bash

EMOJI_FILE=~/.local/share/emoji
chosen=$(cat $EMOJI_FILE | dmenu -i -l 25 | awk '{print $1}' | tr -d '\n')

[[ -z "$chosen" ]] && exit
printf "$chosen" | xclip -selection clipboard && 
notify-send "'$chosen' copied to clipboard."
