#!/usr/bin/env bash

primary=eDP1
secondary=DP1

choice=$(echo -e "Primary\nSecondary\nExtend\nMirror" | dmenu -i -p 'Pick a monitor:')

case "$choice" in
    Primary) xrandr --output $primary --auto --output $secondary --off & ;;
    Secondary) xrandr --output $secondary --auto --output $primary --off & ;;
    Extend) xrandr --output $primary --auto --output $secondary --auto --above $primary & ;;
    Mirror) xrandr --output $primary --auto --output $secondary --auto --same-as $primary & ;;
esac
